MODE_LOCAL = 'local'
MODE_CLUSTER = 'cluster'


MODULE_MSC = "MSC"
MODULE_IFS = "IFS"
MODULE_MCI = "MCI"
MODULE_CPIC = "CPIC"
MODULE_HSTDM = "HSTDM"

MODULE_IDS = [MODULE_MSC, MODULE_IFS, MODULE_MCI, MODULE_CPIC, MODULE_HSTDM]
